### PR TITLE
add Rivendell Radio Automation

### PR DESCRIPTION
**Pull request by deedos**

### CODE REVIEW

**Comment by barroco** [comment]
Hi @deedos, 

Thank you for your contribution. Happy to add it. However, could you please remove the additional links and just use a simple description as the other entries ?

Thank you,
Michael

**Comment by deedos** [comment]
Hi michael. Can I maintain the wiki url ? It's improtant because tha main
site do not link to it. I can remove the list of stations url. All right ?
cheers

2016-06-17 12:12 GMT-03:00 Michael Barroco <notifications@github.com>:

> Hi @deedos <https://github.com/deedos>,
>
> Thank you for your contribution. Happy to add it. However, could you
> please remove the additional links and just use a simple description as the
> other entries ?
>
> Thank you,
> Michael
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ebu/awesome-broadcasting/pull/48#issuecomment-226796368>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AALSpLBRDyY-WbVjf9H8N6WSJCpgdg0Fks5qMrlhgaJpZM4I4ct4>
> .
>



-- 
Daniel Roviriego
(21) 972361654

**Comment by barroco** [comment]
Sorry, no. Simple description and no additional link.

**Comment by barroco** [comment]
Thank you! 👍

**Pull request merged**
