### PR TITLE
Subtitle edit

### PR DESCRIPTION
**Pull request by MarcoNPO**
An editor for video subtitles
http://www.nikse.dk/SubtitleEdit

### CODE REVIEW

**Comment by barroco** [comment]
Hello @MarcoNPO ,
The pull request looks broken, how did you proceed to make these changes?
Kind regards,
Michael

**Comment by MarcoNPO** [comment]
Dear Michael,

Did it most probably wrong.
The idea was to submit the following link tot he list:

Subtitle Edit
An open source editor for video subtitles
http://www.nikse.dk/subtitleedit/

Best regards,
Marco

Van: Michael Barroco <notifications@github.com>
Beantwoorden - Aan: ebu/awesome-broadcasting <reply@reply.github.com>
Datum: dinsdag 14 februari 2017 09:38
Aan: ebu/awesome-broadcasting <awesome-broadcasting@noreply.github.com>
CC: NPO <Marco.Slik@NPO.nl>, Mention <mention@noreply.github.com>
Onderwerp: Re: [ebu/awesome-broadcasting] Subtitle edit (#60)


Hello @MarcoNPO<https://github.com/MarcoNPO> ,
The pull request looks broken, how did you proceed to make these changes?
Kind regards,
Michael

**Comment by ebuio** [comment]
Hi Marco,

I can show you how to make it if you are interested on a Webex.

Kind regards,
Michael
________________________________

**Comment by MarcoNPO** [comment]
Dear Michael,

I am sorry for not coming back to you earlier. I was ill.
Are you able to show me early this afternoon?

Marco

Van: ebuio [mailto:notifications@github.com]
Verzonden: dinsdag 14 februari 2017 9:45
Aan: ebu/awesome-broadcasting
CC: Marco Slik; Mention
Onderwerp: Re: [ebu/awesome-broadcasting] Subtitle edit (#60)

Hi Marco,

I can show you how to make it if you are interested on a Webex.

Kind regards,
Michael
________________________________

**Comment by frans-ebu** [comment]
Tnx @MarcoNPO I have updated the list in a separate commit.

**Comment by MarcoNPO** [comment]
Dank Frans.
Lesje git zou ooit best nuttig zijn ;-)




Verzonden vanaf mijn mobiel. Excuses voor het korte bericht en eventuele typefouten.

Marco Slik


-------- Oorspronkelijk bericht --------
Van: Frans de Jong <notifications@github.com>
Datum: 27-03-17 11:22 (GMT+01:00)
Aan: ebu/awesome-broadcasting <awesome-broadcasting@noreply.github.com>
Cc: Marco Slik <Marco.Slik@NPO.nl>, Mention <mention@noreply.github.com>
Onderwerp: Re: [ebu/awesome-broadcasting] Subtitle edit (#60)


Tnx @MarcoNPO<https://github.com/MarcoNPO> I have updated the list in a separate commit.

**Pull request closed without merging**
