### PR TITLE
Added an entry for the Turing codec under codecs

### PR DESCRIPTION
**Pull request by matteonaccari**
As discussed with Michael Barroco, here is the pull request to add the entry for Turing codec in the codecs section.

### CODE REVIEW

**Comment by barroco** [comment]
👍 Thanks!

**Comment by annci62** [comment]
Hello matteonaccari,

I have download these codec, but they can NOT compiled. Error is reported:
turingcodec/havoc/pred_inter.h:35: error：expected unqualified-id before ‘using’

g++ version:4.4.7
contos 6.5
Could you tell me how to resolve this problem?Thank you very much

**Comment by barroco** [comment]
Hello @annci62, I would recommend to use the [issue tracker of the project](https://github.com/bbc/turingcodec.git) to contact @matteonaccari:

https://github.com/bbc/turingcodec.git

**Comment by annci62** [comment]
@barroco Thank you very much

**Pull request merged**
