### PR TITLE
Add PiRSClock-Full

### PR DESCRIPTION
**Pull request by peternewman**
Create a new category and move PiClock into it too

### CODE REVIEW

**Review by frans-ebu — COMMENTED** [review]
Thank you @peternewman. I am having difficulty finding the licence info on the PiClock project. Can you point me to it?

**Comment by peternewman** [comment]
> Thank you @peternewman. I am having difficulty finding the licence info on the PiClock project. Can you point me to it?

Hmm agreed. It slipped under the net in #120 . Let me chase that up.

I've raised https://github.com/simonhyde/PiClock/issues/7 to track it.

Hopefully that will be sorted soon, otherwise I'm not quite sure what to do with the other parts of this PR (and #155)...

**Comment by peternewman** [comment]
Hi @frans-ebu ,

This has now been done in https://github.com/simonhyde/PiClock/commit/398dc291a310ef15f1d3aa8610e7dadb60f23515

**Comment by peternewman** [comment]
Bump @frans-ebu ? Have you had a chance to take another look at this please?

**Review by magicbadger — APPROVED** [review]

**Comment by peternewman** [comment]
Thanks @magicbadger !

**Pull request merged**
